name: PR_labeler
on: 
  issues:
    types: [opened, edited, milestoned]
  pull_request_target:
    types: [opened, ublabeled, reopened,converted_to_draft,ready_for_review]

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Check Labels
      id: labeler
      uses: jimschubert/labeler-action@v2
      with:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
